name: push
on: 
  push:
    branches:
      - master
      - main
    tags:        
      - v*

jobs:
  call-workflow:
    uses: raf-backstage-demo/shared-workflows/.github/workflows/quarkus.yaml@main
    secrets:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}