apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  tags:
    - java
    - quarkus
  links:
    - url: https://codeready-openshift-workspaces.apps.tmp-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/${{values.artifact_id}}
      title: Code Ready Workspaces
      icon: web    
  annotations:
    github.com/project-slug: raf-backstage-demo/${{values.artifact_id}}
    'backstage.io/kubernetes-id': ${{values.artifact_id}}
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=${{values.artifact_id}}'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}