---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.database_id }}-qa
  namespace: ${{values.application_id.split(":")[1]}}-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/shared-workflows
    chart: cockroach-serverless
    targetRevision: '0.1.0'
    helm:
      values: |
        application: ${{values.application_id.split(":")[1]}} 
        environment: qa
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application_id.split(":")[1]}}-qa
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy                     