apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include ".helm.serviceAccountName" . }}
  name: github-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ printf "{\"ghcr.io\":{\"username\": \"%s\", \"password\": \"%s\", \"email\":\"serviceaccount@example.org\"}}" .Values.repo.username .Values.repo.password | b64enc }}
    
