{{- define "metric_labels.array" -}}
{{ range $key,$value := . -}} 
{{ $key }}: "{{ $value }}" 
{{- end }}
{{- end -}}

{{- $this_destination_service := (list (default .Chart.Name .Values.nameOverride) .Release.Namespace "svc.cluster.local") | join "." }}

{{- $labels := dict "destination_service_namespace" .Release.Namespace}}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $this_destination_service }}-alerts
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include ".helm.selectorLabels" . | nindent 8 }}
spec:
  groups:
  - name: SLOs-{{ $this_destination_service }}
    rules:  
  {{- $params := .Values }}
  {{- $destination_service := $this_destination_service | replace "." "_" }}
  {{- range $alert_key,$alert := .Values.alerts -}}
  {{- range $speed_key,$speed := $alert.speeds -}}
  {{- range $window_key,$window := $speed.windows }}    
      - expr: |
          ( 
            sum(rate(istio_request_duration_seconds_count{connection_security_policy!="none",destination_service="{{ $this_destination_service }}"}[{{ $window }}])) -
            sum(rate(istio_request_duration_seconds_bucket{connection_security_policy!="none",destination_service="{{ $this_destination_service }}",response_code!~"5.*",le="{{ $params.latency }}"}[{{ $window }}]))
          )
          /
          sum(rate(istio_request_duration_seconds_count{connection_security_policy!="none",destination_service="{{ $this_destination_service }}"}[{{ $window }}]))
        labels:
          {{ template "metric_labels.array" $labels }}
          service: {{ $this_destination_service }}
        record: virtual_service:{{ $destination_service }}:error_rate_{{ $window }}
  {{- end -}}
  {{- end }}
      - alert: ErrorBudgetBurn
        expr: |
          (
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.fast.windows.long }} > ({{ $alert.speeds.fast.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
            and
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.fast.windows.short }} > ({{ $alert.speeds.fast.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
          )
          or
          (
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.slow.windows.long }} > ({{ $alert.speeds.slow.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
            and
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.slow.windows.short }} > ({{ $alert.speeds.slow.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
          )
        labels:
          {{ template "metric_labels.array" $labels }}
          severity: {{ $alert.severity }}
          service: {{ $this_destination_service }}
  {{- end -}}