apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.resource_id}}
  description: a Fedora VM
spec:
  type: virtual-machine
  owner: ${{values.owner}}
  system: ${{values.application_id}}