---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: ${{values.application.split(":")[1]}}-dev
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/${{ values.component_id }}
    targetRevision: HEAD
    path: .helm/chart
    helm:
      value_files:
        - ./helm/value-files/values-dev.yaml
      values: | 
        image:
          tag: dummy
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split(":")[1]}}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: ${{values.application.split(":")[1]}}-qa
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/${{ values.component_id }}
    targetRevision: HEAD
    path: .helm/chart
    helm:
      value_files:
        - ./helm/value-files/values-qa.yaml
      values: | 
        image:
          tag: dummy
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split(":")[1]}}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: ${{values.application.split(":")[1]}}-prod
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/${{ values.component_id }}
    targetRevision: HEAD
    path: .helm/chart
    helm:
      value_files:
        - ./helm/value-files/values-prod.yaml
      values: | 
        image:
          tag: dummy
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split(":")[1]}}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy                